name: Gymnathlon Checker

run-name: ${{ inputs.daily_report == true && 'Gymnathlon Checker — Daily Report' || 'Gymnathlon Checker — Checker' }}

on:
  push:
    branches:
      - main

  # GitHub Scheduled Workflow
  # schedule:
  #   - cron: '7,22,37,52 * * * *'

  workflow_dispatch:
    inputs:
      daily_report:
        description: 'Send Daily report'
        required: false
        default: false
        type: boolean

jobs:
  check-gymnathlon:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Create Gmail credentials
        run: |
          echo '${{ secrets.GMAIL_CREDENTIALS }}' > credentials.json
          echo '${{ secrets.GMAIL_TOKEN }}' > token.json

      - name: Run Gymnathlon checker
        run: |
          if [ "${{ inputs.daily_report }}" = "true" ]; then
            node monitor.js --daily-report
          else
            node monitor.js
          fi

      - name: Save state
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [ -f state.json ]; then
            git add -f state.json

            if git diff --cached --quiet; then
              echo "State sa nezmenil."
            else
              git commit -m "Update checker state"
              git push
            fi
          else
            echo "state.json neexistuje - nie je co ulozit."
          fi
